# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [10]:
# Import libraries
import numpy as np
import pandas as pd

In [11]:
# Importing the dataset from Ironhack's database
pokemon = pd.read_csv('Pokemon.csv')
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [12]:
# your code here

#the formula to compute Total
pokemon['Total_check']= pokemon.iloc[:,5:11].sum(axis=1)

#which check if Total is calculatec correctly
#It is because the df below, checking if column Total_check equals column Toal, is empty
pokemon.loc[pokemon['Total_check'] != pokemon['Total']]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary, Total_check]
Index: []

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [13]:
# create dummised 
# pokemon_dummies = pd.get_dummies(pokemon, columns = ['Type 1', 'Type 2'])

pokemon_dummies = pd.get_dummies(pokemon['Type 1']) + pd.get_dummies(pokemon['Type 2'])
pokemon_dummies['Total'] = pokemon['Total']
pokemon_dummies.head()

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,Total
0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,318
1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,405
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,525
3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,625
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,309

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [14]:
# your code here
pokemon_corr = pokemon_dummies
pokemon_corr.head()

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,Total
0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,318
1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,405
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,525
3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,625
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,309

In [15]:
correlations = pokemon_corr.corr().reset_index()
correlations.head()

,index,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,Total
0,Bug,1.000000,-0.082062,-0.081200,-0.045111,-0.072148,-0.048645,-0.060536,0.064571,-0.058915,-0.034430,-0.063544,-0.070229,-0.120219,0.121210,-0.111968,-0.003706,0.047178,-0.123983,-0.145781
1,Dark,-0.082062,1.000000,-0.003963,-0.067375,-0.059864,-0.007791,-0.020368,-0.022164,0.001484,-0.048339,-0.023480,-0.010163,-0.099751,-0.018227,-0.044327,-0.033493,-0.023978,-0.028548,0.056154
2,Dragon,-0.081200,-0.003963,1.000000,-0.024000,-0.035541,-0.068775,-0.038069,0.026237,-0.019410,-0.078818,0.052430,0.015173,-0.098702,-0.055525,-0.026557,-0.032360,-0.044417,-0.083285,0.229705
3,Electric,-0.045111,-0.067375,-0.024000,1.000000,-0.035541,-0.068775,-0.057104,-0.020407,-0.041592,-0.078818,-0.059420,-0.033382,-0.067737,-0.074838,-0.091928,-0.072188,-0.001346,-0.069109,0.020971
4,Fairy,-0.072148,-0.059864,-0.035541,-0.035541,1.000000,-0.061108,-0.067651,-0.052669,-0.056665,-0.048756,-0.069360,-0.051232,-0.001720,-0.066495,0.027227,0.002212,0.013155,-0.067703,-0.036698

In [16]:
correlations[['index','Total']].sort_values(["Total"], ascending = False).head()

      index     Total
18    Total  1.000000
2    Dragon  0.229705
14  Psychic  0.124688
16    Steel  0.109703
6      Fire  0.078726

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [8]:
# your code here
"""
the correlation between Total and Type 1 and Type 2 is low, however under current assumptions let us 
choose Type 1 Dragon and Type 2 Fighting
"""

pokemon_selected = pokemon.loc[(pokemon['Type 1'] == 'Dragon') | (pokemon['Type 2'] == 'Fighting')]

num=pokemon_selected.shape[0]
print(f'Number of potential pokemons is {num}, and these pokemons are: ')
pokemon.loc[(pokemon['Type 1'] == 'Dragon') | (pokemon['Type 2'] == 'Fighting')]

Number of potential pokemons is 58, and these pokemons are:

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_check
67,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False,510
159,147,Dratini,Dragon,NaN,300,41,64,45,50,50,50,1,False,300
160,148,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False,420
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False,600
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,780
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False,500
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False,600
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False,405
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False,530
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False,630
310,286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False,460
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False,490
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False,590
406,371,Bagon,Dragon,NaN,300,45,75,60,40,30,50,3,False,300
407,372,Shelgon,Dragon,NaN,420,65,95,100,60,50,50,3,False,420
408,373,Salamence,Dragon,Flying,600,95,135,80,110,80,100,3,False,600
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,700
417,380,Latias,Dragon,Psychic,600,80,80,90,110,130,110,3,True,600
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True,700
419,381,Latios,Dragon,Psychic,600,80,90,80,130,110,110,3,True,600
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True,700
425,384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True,680
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,780
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False,405
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False,534
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False,580
491,443,Gible,Dragon,Ground,300,58,70,45,40,45,42,4,False,300
492,444,Gabite,Dragon,Ground,410,68,90,65,50,55,82,4,False,410
493,445,Garchomp,Dragon,Ground,600,108,130,95,80,85,102,4,False,600
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False,700
503,453,Croagunk,Poison,Fighting,300,48,61,40,61,40,50,4,False,300
504,454,Toxicroak,Poison,Fighting,490,83,106,65,86,65,85,4,False,490
526,475,Gallade,Psychic,Fighting,518,68,125,65,65,115,80,4,False,518
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False,618
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False,418
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False,528
620,559,Scraggy,Dark,Fighting,348,50,75,70,35,70,48,5,False,348
621,560,Scrafty,Dark,Fighting,488,65,90,115,45,115,58,5,False,488
671,610,Axew,Dragon,NaN,320,46,87,60,30,40,57,5,False,320
672,611,Fraxure,Dragon,NaN,410,66,117,70,40,50,67,5,False,410
673,612,Haxorus,Dragon,NaN,540,76,147,90,60,70,97,5,False,540
682,621,Druddigon,Dragon,NaN,485,77,120,90,60,90,48,5,False,485
699,638,Cobalion,Steel,Fighting,580,91,90,129,90,72,108,5,True,580
700,639,Terrakion,Rock,Fighting,580,91,129,90,72,90,108,5,True,580
701,640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True,580
706,643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True,680
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True,680
710,646,Kyurem,Dragon,Ice,660,125,130,90,130,90,95,5,True,660
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True,700
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True,700
713,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False,580
714,647,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False,580
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False,600
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False,530
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False,300
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False,452
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False,600
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True,600

In [9]:
#expected Total mean
mn = pokemon_selected['Total'].mean()
print(f'Expected Total mean is: {mn}')

Expected Total mean is: 539.4655172413793

# Let us iterate again to see of we can get more specific results

# Does combination of Type 1 & Type 2 gives better correlations?

In [10]:
#let us re-use Combo typw form Challenge 1
pokemon2 = pd.read_csv('Pokemon.csv')
pokemon2.loc[(pokemon2['Type 1'].isnull() == False) & (pokemon2['Type 2'].isnull() == False),'Combo Type'] = pokemon2['Type 1'] + "-" + pokemon2['Type 2']
pokemon2.loc[(pokemon2['Type 1'].isnull() == False) & (pokemon2['Type 2'].isnull() == True),'Combo Type'] = pokemon2['Type 1']
pokemon2.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Grass-Poison
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Fire

In [11]:
pokemon2_dummies = pd.get_dummies(pokemon2, columns = ['Combo Type'])
pokemon2_dummies.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,...,Combo Type_Water-Fighting,Combo Type_Water-Flying,Combo Type_Water-Ghost,Combo Type_Water-Grass,Combo Type_Water-Ground,Combo Type_Water-Ice,Combo Type_Water-Poison,Combo Type_Water-Psychic,Combo Type_Water-Rock,Combo Type_Water-Steel
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,0,0,0,0,0,0,0,0,0,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,0,0,0,0,0,0,0,0,0,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,0,0,0,0,0,0,0,0,0,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,...,0,0,0,0,0,0,0,0,0,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,0,0,0,0,0,0,0,0,0,0

In [12]:
pokemon_corr2 = pd.concat([pokemon2_dummies['Total'], pokemon2_dummies.iloc[:,13:]], axis = 1)
pokemon_corr2.head()

,Total,Combo Type_Bug,Combo Type_Bug-Electric,Combo Type_Bug-Fighting,Combo Type_Bug-Fire,Combo Type_Bug-Flying,Combo Type_Bug-Ghost,Combo Type_Bug-Grass,Combo Type_Bug-Ground,Combo Type_Bug-Poison,...,Combo Type_Water-Fighting,Combo Type_Water-Flying,Combo Type_Water-Ghost,Combo Type_Water-Grass,Combo Type_Water-Ground,Combo Type_Water-Ice,Combo Type_Water-Poison,Combo Type_Water-Psychic,Combo Type_Water-Rock,Combo Type_Water-Steel
0,318,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,405,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,525,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,625,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,309,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
correlations2 = pokemon_corr2.corr().reset_index()
correlations2.head()

,index,Total,Combo Type_Bug,Combo Type_Bug-Electric,Combo Type_Bug-Fighting,Combo Type_Bug-Fire,Combo Type_Bug-Flying,Combo Type_Bug-Ghost,Combo Type_Bug-Grass,Combo Type_Bug-Ground,...,Combo Type_Water-Fighting,Combo Type_Water-Flying,Combo Type_Water-Ghost,Combo Type_Water-Grass,Combo Type_Water-Ground,Combo Type_Water-Ice,Combo Type_Water-Poison,Combo Type_Water-Psychic,Combo Type_Water-Rock,Combo Type_Water-Steel
0,Total,1.000000,-0.178699,-0.016537,0.047979,0.008309,-0.017369,-0.058753,-0.037054,-0.037625,...,0.062210,-0.024374,-0.011526,-0.045257,-0.001128,0.039182,-0.004317,0.030361,-0.003756,0.028003
1,Combo Type_Bug,-0.178699,1.000000,-0.007377,-0.007377,-0.007377,-0.019665,-0.005213,-0.012809,-0.007377,...,-0.009040,-0.013844,-0.007377,-0.009040,-0.016578,-0.009040,-0.009040,-0.011685,-0.010445,-0.005213
2,Combo Type_Bug-Electric,-0.016537,-0.007377,1.000000,-0.002506,-0.002506,-0.006681,-0.001771,-0.004352,-0.002506,...,-0.003071,-0.004704,-0.002506,-0.003071,-0.005632,-0.003071,-0.003071,-0.003970,-0.003549,-0.001771
3,Combo Type_Bug-Fighting,0.047979,-0.007377,-0.002506,1.000000,-0.002506,-0.006681,-0.001771,-0.004352,-0.002506,...,-0.003071,-0.004704,-0.002506,-0.003071,-0.005632,-0.003071,-0.003071,-0.003970,-0.003549,-0.001771
4,Combo Type_Bug-Fire,0.008309,-0.007377,-0.002506,-0.002506,1.000000,-0.006681,-0.001771,-0.004352,-0.002506,...,-0.003071,-0.004704,-0.002506,-0.003071,-0.005632,-0.003071,-0.003071,-0.003970,-0.003549,-0.001771

In [14]:
correlations2[['index','Total']].sort_values(["Total"], ascending = False)

                           index     Total
0                          Total  1.000000
26      Combo Type_Dragon-Flying  0.149777
28         Combo Type_Dragon-Ice  0.128737
29     Combo Type_Dragon-Psychic  0.127066
113  Combo Type_Psychic-Fighting  0.104173
..                           ...       ...
102            Combo Type_Poison -0.064380
95       Combo Type_Normal-Fairy -0.069525
9          Combo Type_Bug-Poison -0.089742
97      Combo Type_Normal-Flying -0.092626
1                 Combo Type_Bug -0.178699

[155 rows x 2 columns]

In [15]:
#In this result the correlations are also week, but we get a shorter list 
pokemon2_selected = pokemon2.loc[(pokemon2['Combo Type'] == 'Dragon-Flying')]
pokemon2_selected

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Combo Type
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False,Dragon-Flying
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False,Dragon-Flying
408,373,Salamence,Dragon,Flying,600,95,135,80,110,80,100,3,False,Dragon-Flying
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,Dragon-Flying
425,384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True,Dragon-Flying
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,Dragon-Flying

In [16]:
#expected Total mean, also seems to be higher vs first iterations of analysis
mn2 = pokemon2_selected['Total'].mean()
print(f'Expected Total mean is: {mn2}')

Expected Total mean is: 641.6666666666666

# Exploration

In [17]:
df = pokemon.groupby(['Type 1','Type 2'])['Total'].agg(['mean','count']).reset_index()
df
df.sort_values(['mean'], ascending=False)

      Type 1  Type 2        mean  count
70    Ground    Fire  770.000000      1
24    Dragon     Ice  686.666667      3
114    Steel  Dragon  680.000000      1
52     Ghost  Dragon  680.000000      2
95   Psychic    Dark  680.000000      1
..       ...     ...         ...    ...
88    Poison     Bug  330.000000      1
81    Normal   Fairy  330.000000      5
94    Poison   Water  320.000000      1
10       Bug   Water  269.000000      1
4        Bug   Ghost  236.000000      1

[136 rows x 4 columns]